name: Golden Insights
favicon: null
layout_spectrum: 0.24654
typography_spectrum: 0.12714
title: 'Golden Insights: My thoughts about managing, creativity, and business (stuff)'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FEFEFE'
    - '#545C30'
    - '#02010D'
    - '#F3C6AB'
    - '#C69177'
  brandStrength: 0.1875
  lightness: 0.672043
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
